### ISSUE TITLE
email and web hyperlinks backwards in template

### ISSUE THREAD

**Issue by jeffgerickson** [lukeolson/illinois-letterhead#5]
In the template letter, replace the line lines

`\providecommand\fromemail{\url{netid@illinois.edu}}
\providecommand\fromweb{\href{http://netid.cs.illinois.edu}{netid.cs.illinois.edu}}`

with the lines

`\providecommand\fromemail{\href{mailto:netid@illinois.edu}{netid@illinois.edu}}
\providecommand\fromweb{\url{http://netid.cs.illinois.edu}}`

The `\url` macro uses its argument both as text and as a hyperlink target, and raw email addresses are not valid hyperlink targets.

**Comment by lukeolson** [comment]
thanks.  fixed email with mailto in 620a32c15b9297a2dedef1274be7e6dde79f0899

(left `\fromweb` as-is for now)
